#!/bin/bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


DOT_FILE_NAMES=(
    ".gitconfig"
    ".gitignore_global"
    ".zshrc"
    ".zshrc.local"
    ".zshrc_aliases"
    "Brewfile"
    ".git_aliases"
)

link_dotfiles() {
    for filename in "${DOT_FILE_NAMES[@]}"; do
        source_file="$SCRIPT_PATH/$filename"
        target_file="$HOME/$filename"
        
        if [ ! -f "$source_file" ]; then
            echo "Source file '$source_file' does not exist. Skipping..."
            continue
        fi
        
        ln -s -v "$source_file" "$target_file"
    done
}

unlink_dotfiles() {
    for filename in "${DOT_FILE_NAMES[@]}"; do
        dotfile="$HOME/$filename"
        rm -f -v "$dotfile"
    done
}

update_links() {
    echo "Removing symlinks..."
    unlink_dotfiles

    echo "Creating symlinks..."
    link_dotfiles
}

update_links
