#!/bin/sh

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Hide all icons from desktop
defaults write com.apple.finder CreateDesktop -bool FALSE

defaults write -g NSNavPanelExpandedStateForSaveMode -boolean true

defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

defaults write com.apple.finder AppleShowAllFiles -bool true

defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$SCRIPT_PATH/iterm"

defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

defaults write -g com.apple.swipescrolldirection -bool FALSE

killall Finder

killall Dock