#!/bin/sh

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOT_FILES_PATH=$SCRIPT_PATH/../dotfiles

DOT_FILE_NAMES=()
for file in $DOT_FILES_PATH/.*
do
    filename=$(basename $file)

    black_list=("." ".." ".DS_Store" "README.md")
    for black_list_name in ${black_list[@]}
    do
        if [ $black_list_name == $filename ]; then
            continue 2
        fi
    done

    DOT_FILE_NAMES+=($filename)
done

link_dotfiles() {
    for filename in ${DOT_FILE_NAMES[@]}
    do
        ln -s -v $DOT_FILES_PATH/$filename $HOME/$filename
    done
}

unlink_dotfiles() {
    for filename in ${DOT_FILE_NAMES[@]}
    do
        dotfile=$HOME/$filename

        if [ -e $dotfile ]; then
            rm -rf -v $dotfile
        fi
    done
}

update_links() {
    echo "Removing symlinks..."
    unlink_dotfiles

    echo "Creating symlinks..."
    link_dotfiles
}
export -f update_links