#!/usr/bin/env bash

help() {
  if [[ "$#" -gt 0 ]]; then
    echo "$@"
    echo
  fi
  echo "tq query"
  exit "$#"
}

if [[ -z "$THANOS_URL" ]]; then
  echo "Error: THANOS_URL environment variable is not defined."
  exit 1
fi

if [[ "$#" -lt 1 ]]; then
  help
fi

if ! curl -sS --get "http://${THANOS_URL}/api/v1/query" --data-urlencode "query=$*" | jq '.data.result[]' ; then
  curl -sS --get "http://${THANOS_URL}/api/v1/query" --data-urlencode "query=$*" | jq .
fi
